const GENERATION = {
  FETCH: 'GENERATION_FETCH',
  FETCH_ERROR: 'GENERATION_FETCH_ERROR',
  FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

const DRAGON = {
  FETCH: 'DRAGON_FETCH',
  FETCH_ERROR: 'DRAGON_FETCH_ERROR',
  FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
};

const ACCOUNT = {
  FETCH: 'ACCOUNT_FETCH',
  FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
  FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
  FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

export { GENERATION, DRAGON, ACCOUNT };