const GENERATION = {
  FETCH: 'GENERATION_FETCH',
  FETCH_ERROR: 'GENERATION_FETCH_ERROR',
  FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

const DRAGON = {
  FETCH: 'DRAGON_FETCH',
  FETCH_ERROR: 'DRAGON_FETCH_ERROR',
  FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
};

export { GENERATION, DRAGON };